"use client";

import { useState } from "react";
import { Download, Link2, Check, ChevronDown } from "lucide-react";

type Props = {
  title: string;
  content: string;
};

export default function ExportReportButton({ title, content }: Props) {
  const [open, setOpen] = useState(false);
  const [copied, setCopied] = useState(false);

  const downloadHTML = () => {
    const html = `<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${title} - Zentrade</title>
<style>body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;max-width:800px;margin:40px auto;padding:0 20px;color:#1a1a2e;line-height:1.7}h1{color:#6366f1;border-bottom:2px solid #6366f1;padding-bottom:8px}h2{color:#374151;margin-top:24px}code{background:#f3f4f6;padding:2px 6px;border-radius:4px;font-size:.9em}strong{color:#1f2937}.badge{background:#6366f1;color:white;padding:4px 12px;border-radius:20px;font-size:12px;font-weight:600}.footer{margin-top:40px;padding-top:16px;border-top:1px solid #e5e7eb;color:#9ca3af;font-size:12px}</style>
</head><body>
<h1>${title} <span class="badge">Zentrade AI</span></h1>
<p style="color:#9ca3af;font-size:13px">Generated: ${new Date().toLocaleString()}</p>
<div>${content.replace(/\n/g, "<br>")}</div>
<div class="footer">Generated by Zentrade AI Agent OS</div>
</body></html>`;

    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${title.replace(/[^a-zA-Z0-9]/g, "-").toLowerCase()}-report.html`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    setOpen(false);
  };

  const copyShareLink = () => {
    const shareId = `share-${Date.now()}`;
    try {
      localStorage.setItem(`zentrade_share_${shareId}`, JSON.stringify({ title, content }));
      const link = `${window.location.origin}/report?id=${shareId}`;
      navigator.clipboard.writeText(link);
      setCopied(true);
      setTimeout(() => { setCopied(false); setOpen(false); }, 2000);
    } catch {}
  };

  return (
    <div className="relative">
      <button
        onClick={() => setOpen(!open)}
        className="flex items-center gap-1 p-1.5 rounded-lg text-[var(--ink-muted)] hover:text-[var(--accent-2)] hover:bg-[color-mix(in_srgb,var(--accent-2)_8%,transparent)] transition-colors"
        title="Export report"
      >
        <Download size={13} />
        <ChevronDown size={9} />
      </button>
      {open && (
        <div className="absolute right-0 top-full mt-1 w-44 glass-card py-1 z-50" style={{ boxShadow: "0 8px 24px rgba(0,0,0,.15)" }}>
          <button
            onClick={downloadHTML}
            className="w-full flex items-center gap-2 px-3 py-2 text-xs text-[var(--ink)] hover:bg-[color-mix(in_srgb,var(--accent-2)_8%,transparent)] transition-colors"
          >
            <Download size={12} />
            Download Report
          </button>
          <button
            onClick={copyShareLink}
            className="w-full flex items-center gap-2 px-3 py-2 text-xs text-[var(--ink)] hover:bg-[color-mix(in_srgb,var(--accent-2)_8%,transparent)] transition-colors"
          >
            {copied ? <Check size={12} className="text-[var(--positive)]" /> : <Link2 size={12} />}
            {copied ? "Link Copied!" : "Copy Share Link"}
          </button>
        </div>
      )}
    </div>
  );
}
