export function exportAsHTML(title: string, markdownContent: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${title} - Zentrade Report</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 40px auto; padding: 0 20px; color: #1a1a2e; line-height: 1.7; }
  h1 { color: #6366f1; border-bottom: 2px solid #6366f1; padding-bottom: 8px; }
  h2 { color: #374151; margin-top: 24px; }
  h3 { color: #4b5563; }
  code { background: #f3f4f6; padding: 2px 6px; border-radius: 4px; font-size: 0.9em; }
  ul, ol { padding-left: 24px; }
  li { margin: 4px 0; }
  strong { color: #1f2937; }
  .header { display: flex; align-items: center; gap: 12px; margin-bottom: 24px; }
  .badge { background: #6366f1; color: white; padding: 4px 12px; border-radius: 20px; font-size: 12px; font-weight: 600; }
  .timestamp { color: #9ca3af; font-size: 13px; }
  .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e5e7eb; color: #9ca3af; font-size: 12px; }
</style>
</head>
<body>
<div class="header">
  <h1>${title}</h1>
  <span class="badge">Zentrade AI</span>
</div>
<p class="timestamp">Generated: ${new Date().toLocaleString()}</p>
<div>${markdownToHTML(markdownContent)}</div>
<div class="footer">Generated by Zentrade AI Agent OS</div>
</body>
</html>`;
}

function markdownToHTML(md: string): string {
  return md
    .replace(/^### (.+)$/gm, "<h3>$1</h3>")
    .replace(/^## (.+)$/gm, "<h2>$1</h2>")
    .replace(/^# (.+)$/gm, "<h1>$1</h1>")
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/`([^`]+)`/g, "<code>$1</code>")
    .replace(/^[-*] (.+)$/gm, "<li>$1</li>")
    .replace(/(<li>.*<\/li>\n?)+/g, "<ul>$&</ul>")
    .replace(/^\d+\. (.+)$/gm, "<li>$1</li>")
    .replace(/\n\n/g, "</p><p>")
    .replace(/^(?!<[hulo])/gm, "<p>")
    .replace(/(?<![>])$/gm, "</p>");
}

export function downloadReport(title: string, content: string) {
  const html = exportAsHTML(title, content);
  const blob = new Blob([html], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${title.replace(/[^a-zA-Z0-9]/g, "-").toLowerCase()}-report.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function generateShareLink(title: string, content: string): string {
  const data = JSON.stringify({ title, content, ts: Date.now() });
  const encoded = btoa(unescape(encodeURIComponent(data)));
  // Store in localStorage for share links
  const shareId = `share-${Date.now()}`;
  try {
    localStorage.setItem(`zentrade_share_${shareId}`, data);
  } catch { /* ignore */ }
  return `${window.location.origin}/report?id=${shareId}`;
}

export function loadSharedReport(id: string): { title: string; content: string } | null {
  try {
    const raw = localStorage.getItem(`zentrade_share_${id}`);
    if (raw) return JSON.parse(raw);
  } catch { /* ignore */ }
  return null;
}
